### ISSUE TITLE
Need Help For C# on windows 10 with raspberry pi 2

### ISSUE THREAD

**Issue by raditv** [danjperron/mpu6050TestInC#1]
Can you port these samples to C# on windows 10 iot?

**Comment by danjperron** [comment]
I never check IOT on windows using the Pi !  The answer is maybe but I won't. Even if I programmed Instrument for 25 years mainly on embedded windows OS  in c#  and c++(mfc).  Normally  my embedded instrument use  another microcomputer using serial or usb for all the i/o.  I do so many things that I have to choose and windows 10 isn't ready I.M.O.

The FFT stuff should be straigth forward anyway.
