### ISSUE TITLE
MPU6050.cpp:148:13: error: ‘usleep’ was not declared in this scope

### ISSUE THREAD

**Issue by SadCl0wn** [danjperron/mpu6050TestInC#2]
I get this error if I try to compile (I use the makefile)

MPU6050.cpp: In member function ‘void MPU6050::setup()’:
MPU6050.cpp:61:22: error: ‘usleep’ was not declared in this scope
           usleep(1000);
                      ^
MPU6050.cpp: In member function ‘void MPU6050::resetFifo()’:
MPU6050.cpp:148:13: error: ‘usleep’ was not declared in this scope
   usleep(500);

**Comment by danjperron** [comment]
Ok I fixed it!   Please clone it again.

Espérant le tout fonctionnel maintenant.
